name: CD

on:
  push:
    branches: [ main ]   # deploy only from main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # 1️⃣ Checkout repo
      # ------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------
      # 2️⃣ Setup Python
      # ------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # ------------------------
      # 3️⃣ Install dbt (Snowflake)
      # ------------------------
      - name: Install dbt Snowflake adapter
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-snowflake==1.8.2"
          dbt --version

      # ------------------------
      # 4️⃣ Configure dbt profile for PROD
      # ------------------------
      - name: Setup dbt profile
        shell: bash
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'EOL'
          banking_dbt:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ACCOUNTADMIN
                database: BANKING
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: ANALYTICS
                threads: 4
          EOL

      # ------------------------
      # 5️⃣ Deploy dbt project
      # ------------------------
      - name: Run dbt build (includes run + test)
        working-directory: banking_dbt
        run: |
          dbt deps
          dbt build --target prod
